// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: buckets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveObjectsInBucket = `-- name: CountLiveObjectsInBucket :one
SELECT count(*)
FROM objects o
JOIN object_versions v ON v.id = o.current_version_id
WHERE o.bucket_id = $1 AND v.is_delete_marker = false
`

// A bucket is "empty" when no object still points at a live version. Objects
// whose current version is a delete marker do not count.
func (q *Queries) CountLiveObjectsInBucket(ctx context.Context, bucketID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveObjectsInBucket, bucketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (name, owner_id)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, owner_id, created_at
`

type CreateBucketParams struct {
	Name    string
	OwnerID pgtype.UUID
}

// DO NOTHING rather than DO UPDATE: a bucket name is global, and silently
// returning someone else's bucket would hand them another user's data. A nil
// result means "taken", and the caller then checks who owns it.
func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket, arg.Name, arg.OwnerID)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBucket = `-- name: DeleteBucket :execrows
DELETE FROM buckets WHERE id = $1 AND owner_id = $2
`

type DeleteBucketParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteBucket(ctx context.Context, arg DeleteBucketParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBucket, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT id, name, owner_id, created_at FROM buckets WHERE name = $1
`

func (q *Queries) GetBucketByName(ctx context.Context, name string) (Bucket, error) {
	row := q.db.QueryRow(ctx, getBucketByName, name)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listBucketsByOwner = `-- name: ListBucketsByOwner :many
SELECT id, name, owner_id, created_at FROM buckets WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListBucketsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, listBucketsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
