// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chunks.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitChunks = `-- name: CommitChunks :exec
UPDATE chunks
SET version_id = $1, state = 'committed'
WHERE id = ANY ($2::uuid[]) AND state <> 'deleted'
`

type CommitChunksParams struct {
	VersionID pgtype.UUID
	ChunkIds  []pgtype.UUID
}

// Absolute assignment, not a state transition, so running it twice is
// harmless. Deleted chunks are excluded so a commit can never resurrect one.
func (q *Queries) CommitChunks(ctx context.Context, arg CommitChunksParams) error {
	_, err := q.db.Exec(ctx, commitChunks, arg.VersionID, arg.ChunkIds)
	return err
}

const listChunksForVersion = `-- name: ListChunksForVersion :many
SELECT id, version_id, chunk_index, size_bytes, sha256, state, created_at FROM chunks
WHERE version_id = $1 AND state = 'committed'
ORDER BY chunk_index
`

func (q *Queries) ListChunksForVersion(ctx context.Context, versionID pgtype.UUID) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, listChunksForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.ChunkIndex,
			&i.SizeBytes,
			&i.Sha256,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStagedChunk = `-- name: UpsertStagedChunk :one
INSERT INTO chunks (id, chunk_index, size_bytes, sha256)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET chunk_index = EXCLUDED.chunk_index
RETURNING id, version_id, chunk_index, size_bytes, sha256, state, created_at
`

type UpsertStagedChunkParams struct {
	ID         pgtype.UUID
	ChunkIndex int32
	SizeBytes  int64
	Sha256     string
}

// The id is supplied by the application, not generated here: it is a
// deterministic UUIDv5 of the upload, part number and content hash, so a
// retried upload of the same bytes resolves to this same row.
func (q *Queries) UpsertStagedChunk(ctx context.Context, arg UpsertStagedChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, upsertStagedChunk,
		arg.ID,
		arg.ChunkIndex,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.ChunkIndex,
		&i.SizeBytes,
		&i.Sha256,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}
