// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: health.sql

package dbgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1 AS ok
`

// Used by GET /health. Proves the database can actually serve a query,
// which is a stronger signal than a connection-level ping: the pool can be
// healthy while the database itself refuses to execute statements.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
