// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: objects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpObjectVersionNo = `-- name: BumpObjectVersionNo :one
UPDATE objects
SET last_version_no = last_version_no + 1, updated_at = now()
WHERE id = $1
RETURNING last_version_no
`

// A relative update, which is normally avoided because retries double-count.
// It is safe here only because the caller holds the upload row lock and has
// already checked that the upload is not yet completed, so this runs at most
// once per upload.
func (q *Queries) BumpObjectVersionNo(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpObjectVersionNo, id)
	var last_version_no int64
	err := row.Scan(&last_version_no)
	return last_version_no, err
}

const createObjectVersion = `-- name: CreateObjectVersion :one
INSERT INTO object_versions (
    object_id, version_no, size_bytes, checksum, content_type, is_delete_marker
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, object_id, version_no, size_bytes, checksum, content_type, is_delete_marker, created_at
`

type CreateObjectVersionParams struct {
	ObjectID       pgtype.UUID
	VersionNo      int64
	SizeBytes      int64
	Checksum       string
	ContentType    string
	IsDeleteMarker bool
}

func (q *Queries) CreateObjectVersion(ctx context.Context, arg CreateObjectVersionParams) (ObjectVersion, error) {
	row := q.db.QueryRow(ctx, createObjectVersion,
		arg.ObjectID,
		arg.VersionNo,
		arg.SizeBytes,
		arg.Checksum,
		arg.ContentType,
		arg.IsDeleteMarker,
	)
	var i ObjectVersion
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionNo,
		&i.SizeBytes,
		&i.Checksum,
		&i.ContentType,
		&i.IsDeleteMarker,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentVersion = `-- name: GetCurrentVersion :one
SELECT v.id, v.object_id, v.version_no, v.size_bytes, v.checksum, v.content_type, v.is_delete_marker, v.created_at
FROM objects o
JOIN object_versions v ON v.id = o.current_version_id
WHERE o.bucket_id = $1 AND o.key = $2
`

type GetCurrentVersionParams struct {
	BucketID pgtype.UUID
	Key      string
}

// The live version of a key. A delete marker is returned rather than hidden,
// so the handler can tell "never existed" (no row) from "deleted" (tombstone)
// and respond 404 for both without guessing.
func (q *Queries) GetCurrentVersion(ctx context.Context, arg GetCurrentVersionParams) (ObjectVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentVersion, arg.BucketID, arg.Key)
	var i ObjectVersion
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.VersionNo,
		&i.SizeBytes,
		&i.Checksum,
		&i.ContentType,
		&i.IsDeleteMarker,
		&i.CreatedAt,
	)
	return i, err
}

const getObjectByKey = `-- name: GetObjectByKey :one
SELECT id, bucket_id, key, current_version_id, last_version_no, created_at, updated_at FROM objects WHERE bucket_id = $1 AND key = $2
`

type GetObjectByKeyParams struct {
	BucketID pgtype.UUID
	Key      string
}

func (q *Queries) GetObjectByKey(ctx context.Context, arg GetObjectByKeyParams) (Object, error) {
	row := q.db.QueryRow(ctx, getObjectByKey, arg.BucketID, arg.Key)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.CurrentVersionID,
		&i.LastVersionNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listObjects = `-- name: ListObjects :many
SELECT o.key, v.size_bytes, v.checksum, v.content_type, v.created_at
FROM objects o
JOIN object_versions v ON v.id = o.current_version_id
WHERE o.bucket_id = $1 AND v.is_delete_marker = false
ORDER BY o.key
LIMIT $2 OFFSET $3
`

type ListObjectsParams struct {
	BucketID pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListObjectsRow struct {
	Key         string
	SizeBytes   int64
	Checksum    string
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListObjects(ctx context.Context, arg ListObjectsParams) ([]ListObjectsRow, error) {
	rows, err := q.db.Query(ctx, listObjects, arg.BucketID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObjectsRow{}
	for rows.Next() {
		var i ListObjectsRow
		if err := rows.Scan(
			&i.Key,
			&i.SizeBytes,
			&i.Checksum,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE objects SET current_version_id = $2, updated_at = now() WHERE id = $1
`

type SetCurrentVersionParams struct {
	ID               pgtype.UUID
	CurrentVersionID pgtype.UUID
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const upsertObject = `-- name: UpsertObject :one
INSERT INTO objects (bucket_id, key)
VALUES ($1, $2)
ON CONFLICT (bucket_id, key) DO UPDATE SET updated_at = now()
RETURNING id, bucket_id, key, current_version_id, last_version_no, created_at, updated_at
`

type UpsertObjectParams struct {
	BucketID pgtype.UUID
	Key      string
}

// DO UPDATE rather than DO NOTHING because it must return the row either way,
// and it takes a row lock held until the transaction ends. That lock is what
// serialises two concurrent writes to the same key.
func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, upsertObject, arg.BucketID, arg.Key)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.CurrentVersionID,
		&i.LastVersionNo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
