// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: uploads.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO multipart_uploads (bucket_id, key, content_type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, bucket_id, key, content_type, status, completed_version_id, created_at, expires_at
`

type CreateUploadParams struct {
	BucketID    pgtype.UUID
	Key         string
	ContentType string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (MultipartUpload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.BucketID,
		arg.Key,
		arg.ContentType,
		arg.ExpiresAt,
	)
	var i MultipartUpload
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.ContentType,
		&i.Status,
		&i.CompletedVersionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUploadForUpdate = `-- name: GetUploadForUpdate :one
SELECT id, bucket_id, key, content_type, status, completed_version_id, created_at, expires_at FROM multipart_uploads WHERE id = $1 FOR UPDATE
`

// FOR UPDATE serialises concurrent completes of the same upload. The second
// caller blocks here, then sees status = 'completed' and returns the recorded
// version instead of creating a second one.
func (q *Queries) GetUploadForUpdate(ctx context.Context, id pgtype.UUID) (MultipartUpload, error) {
	row := q.db.QueryRow(ctx, getUploadForUpdate, id)
	var i MultipartUpload
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.ContentType,
		&i.Status,
		&i.CompletedVersionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listUploadParts = `-- name: ListUploadParts :many
SELECT upload_id, part_no, chunk_id, size_bytes, sha256 FROM upload_parts WHERE upload_id = $1 ORDER BY part_no
`

func (q *Queries) ListUploadParts(ctx context.Context, uploadID pgtype.UUID) ([]UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadParts, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.UploadID,
			&i.PartNo,
			&i.ChunkID,
			&i.SizeBytes,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadCompleted = `-- name: MarkUploadCompleted :exec
UPDATE multipart_uploads
SET status = 'completed', completed_version_id = $2
WHERE id = $1
`

type MarkUploadCompletedParams struct {
	ID                 pgtype.UUID
	CompletedVersionID pgtype.UUID
}

func (q *Queries) MarkUploadCompleted(ctx context.Context, arg MarkUploadCompletedParams) error {
	_, err := q.db.Exec(ctx, markUploadCompleted, arg.ID, arg.CompletedVersionID)
	return err
}

const upsertUploadPart = `-- name: UpsertUploadPart :exec
INSERT INTO upload_parts (upload_id, part_no, chunk_id, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (upload_id, part_no) DO UPDATE
SET chunk_id = EXCLUDED.chunk_id,
    size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256
`

type UpsertUploadPartParams struct {
	UploadID  pgtype.UUID
	PartNo    int32
	ChunkID   pgtype.UUID
	SizeBytes int64
	Sha256    string
}

// Re-uploading a part with identical bytes lands on the same chunk id and
// rewrites the same values, so a retry is a no-op.
func (q *Queries) UpsertUploadPart(ctx context.Context, arg UpsertUploadPartParams) error {
	_, err := q.db.Exec(ctx, upsertUploadPart,
		arg.UploadID,
		arg.PartNo,
		arg.ChunkID,
		arg.SizeBytes,
		arg.Sha256,
	)
	return err
}
